# Generated by Django 2.0.6 on 2018-06-27 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('forename', models.CharField(max_length=100)),
                ('birthDay', models.DateField()),
                ('deathDay', models.DateField()),
                ('nationality', models.CharField(choices=[('FR', 'France'), ('US', 'USA'), ('UK', 'United Kingdom')], max_length=100)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True)),
                ('synopsis', models.TextField(blank=True)),
                ('isbn', models.CharField(blank=True, max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBookList_app.Author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tri', 'trilogie'), ('cyc', 'cyle')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='SerieBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBookList_app.Book')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBookList_app.Serie')),
            ],
            options={
                'verbose_name': 'SerieBook',
                'verbose_name_plural': 'SerieBooks',
            },
        ),
        migrations.AddField(
            model_name='serie',
            name='books',
            field=models.ManyToManyField(through='myBookList_app.SerieBook', to='myBookList_app.Book'),
        ),
    ]
