# Generated by Django 2.0.6 on 2018-06-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBookList_app', '0002_auto_20180627_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='deathDay',
            field=models.DateField(null=True),
        ),
    ]
