# Generated by Django 2.0.6 on 2018-06-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBookList_app', '0004_auto_20180627_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
