# Generated by Django 2.0.5 on 2018-08-04 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myBookList_app', '0006_auto_20180627_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('numberBook', models.PositiveIntegerField(default=0)),
                ('numberAuthor', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listGenres', models.ManyToManyField(db_table='Link_Profil_To_Genre', to='myBookList_app.Genre')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('state', models.CharField(choices=[('toRead', 'à Lire'), ('abandoned', 'abandonné'), ('pending', 'en Attente'), ('onGoing', 'en Cours')], max_length=100)),
                ('note', models.IntegerField()),
                ('comment', models.CharField(max_length=1000)),
                ('readTimes', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBookList_app.Book')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBookList_app.Profil')),
            ],
        ),
        migrations.AlterField(
            model_name='serie',
            name='type',
            field=models.CharField(choices=[('tri', 'trilogie'), ('cyc', 'cycle'), ('sin', 'single')], max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='listGenres',
            field=models.ManyToManyField(db_table='Link_Author_To_Genre', to='myBookList_app.Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='listGenres',
            field=models.ManyToManyField(db_table='Link_Book_To_Genre', to='myBookList_app.Genre'),
        ),
    ]
