# Generated by Django 2.0.5 on 2018-08-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBookList_app', '0007_auto_20180804_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='listGenres',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='listGenres',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='listGenres',
            new_name='genres',
        ),
    ]
