# Generated by Django 2.0.5 on 2018-08-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBookList_app', '0008_auto_20180809_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Livre', 'verbose_name_plural': 'Livres'},
        ),
        migrations.AddField(
            model_name='book',
            name='front_page_cover',
            field=models.ImageField(default=None, height_field=1080, upload_to='myBookList_app/users-datas/front-page-book-cover/', width_field=1280),
        ),
        migrations.AlterField(
            model_name='author',
            name='nationality',
            field=models.CharField(choices=[('FR', 'France'), ('US', 'USA'), ('UK', 'United Kingdom'), ('Ru', 'Russie'), ('Ge', 'Allemagne'), ('Au', 'Autriche')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='state',
            field=models.CharField(choices=[('toRead', 'à Lire'), ('abandoned', 'abandonné'), ('pending', 'en Attente'), ('onGoing', 'en Cours'), ('undefined', 'Non défini')], max_length=100),
        ),
    ]
