# Generated by Django 2.0.7 on 2018-08-29 19:41

from django.db import migrations, models
import myBookList_app.services.BookServices


class Migration(migrations.Migration):

    dependencies = [
        ('myBookList_app', '0009_auto_20180812_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='isDead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='birthDay',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='front_page_cover',
            field=models.ImageField(default=None, max_length=1000, upload_to=myBookList_app.services.BookServices.generate_path_for_save),
        ),
    ]
