# Generated by Django 2.0.7 on 2018-08-29 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBookList_app', '0010_auto_20180829_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.RemoveField(
            model_name='author',
            name='isDead',
        ),
    ]
