# Generated by Django 2.0.7 on 2018-09-02 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBookList_app', '0011_auto_20180829_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='birthDay',
            new_name='birthDate',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='deathDay',
            new_name='deathDate',
        ),
    ]
